'use client';

import { useState } from 'react';
import { AlertTriangle, ArrowRight, CheckCircle2, Database, Gauge, Info, ShieldCheck } from 'lucide-react';
import { DashboardLayout } from '@/components/dashboard/DashboardLayout';
import { TopCommandBar } from '@/components/dashboard/TopCommandBar';
import { useAuditSubReport, useLatestAudit } from '@/lib/use-audit-data';
import type { MRSReport } from '@sitenexis/shared';

function ScoreCard({ label, value, confidence }: { label: string; value: number | null; confidence: number }) {
  return <div className="rounded-xl border border-white/[0.07] bg-deepspace p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs text-[#7A9AB4]">{label}</span><Gauge className="h-4 w-4 text-cyan" /></div><p className="text-2xl font-bold text-white">{value == null ? 'Unavailable' : value}</p><div className="mt-3 h-1.5 rounded-full bg-white/[0.07]"><div className="h-1.5 rounded-full bg-cyan" style={{ width: `${value ?? 0}%` }} /></div><p className="mt-2 text-[10px] text-[#4A6280]">Confidence {Math.round(confidence * 100)}%</p></div>;
}

function IssueChart({ report }: { report: MRSReport }) {
  const total = Math.max(1, report.issueDistribution.reduce((sum, item) => sum + item.value, 0));
  return <div className="rounded-xl border border-white/[0.07] bg-deepspace p-5"><h2 className="mb-1 text-sm font-semibold text-white">Issue distribution</h2><p className="mb-5 text-xs text-[#4A6280]">Counts come from persisted audit findings.</p><div className="space-y-4">{report.issueDistribution.map((item) => <div key={item.label}><div className="mb-1 flex justify-between text-xs"><span className="text-[#94A3B8]">{item.label}</span><span className="text-white">{item.value}</span></div><div className="h-2 rounded-full bg-white/[0.06]"><div className="h-2 rounded-full" style={{ width: `${(item.value / total) * 100}%`, backgroundColor: item.color }} /></div></div>)}</div></div>;
}

export default function MachineResourceStudioPage() {
  const { audit, isLoading: auditLoading } = useLatestAudit();
  const { data: report, isLoading: reportLoading, error } = useAuditSubReport<MRSReport>(audit?.id ?? null, 'machine-resources');
  const [showEvidence, setShowEvidence] = useState(false);

  return <DashboardLayout><TopCommandBar onRunAudit={(domain) => { window.location.href = `/dashboard?domain=${encodeURIComponent(domain)}`; }} /><main className="flex-1 overflow-y-auto px-6 py-8 lg:px-8"><div className="mx-auto max-w-7xl">
    <div className="mb-8 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-cyan"><Database className="h-4 w-4" /> Machine Resource Studio</div><h1 className="text-2xl font-bold tracking-tight text-white">From crawl data to decisions</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#7A9AB4]">MRS converts stored crawl evidence into scores, explanations, risks, and a ranked action plan. It does not create a recommendation without an evidence record.</p></div>{audit && <div className="rounded-lg border border-white/[0.07] bg-white/[0.02] px-4 py-3 text-right"><p className="text-[10px] uppercase tracking-widest text-[#4A6280]">Active audit</p><p className="mt-1 text-sm font-semibold text-white">{audit.domain}</p></div>}</div>
    {(auditLoading || reportLoading) && <div className="rounded-xl border border-white/[0.07] bg-deepspace p-8 text-sm text-[#7A9AB4]">Loading machine resource evidence...</div>}
    {!auditLoading && !audit && <div className="rounded-xl border border-amber/20 bg-amber/5 p-8"><AlertTriangle className="mb-3 h-6 w-6 text-amber" /><h2 className="text-lg font-semibold text-white">No completed audit</h2><p className="mt-2 text-sm text-[#7A9AB4]">Run an audit first. MRS will appear when the audit stores crawl evidence and scores.</p></div>}
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/5 p-6 text-sm text-red-200">MRS could not load this audit. Check the audit status and try again.</div>}
    {report && <div className="space-y-6">
      <section className="rounded-xl border border-cyan/20 bg-cyan/[0.04] p-6"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-cyan"><ShieldCheck className="h-4 w-4" /> Executive summary</div><p className="max-w-4xl text-base leading-7 text-white">{report.executiveSummary}</p><div className="mt-5 grid gap-4 md:grid-cols-2"><div><p className="mb-1 text-xs font-semibold uppercase tracking-widest text-[#4A6280]">Technical explanation</p><p className="text-sm leading-6 text-[#94A3B8]">{report.technicalExplanation}</p></div><div><p className="mb-1 text-xs font-semibold uppercase tracking-widest text-[#4A6280]">AI explanation</p><p className="text-sm leading-6 text-[#94A3B8]">{report.aiExplanation}</p></div></div></section>
      <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold uppercase tracking-widest text-[#7A9AB4]">Score cards</h2><p className="mt-1 text-xs text-[#4A6280]">Each card shows its formula and evidence count.</p></div><span className="text-3xl font-bold text-cyan">{report.overallScore ?? 'N/A'}</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{report.scoreCards.map((score) => <details key={score.key} className="group"><summary className="list-none cursor-pointer"><ScoreCard label={score.label} value={score.value} confidence={score.confidence} /></summary><div className="mt-1 rounded-b-xl border border-t-0 border-white/[0.07] bg-[#0B1620] p-3 text-xs text-[#7A9AB4]"><p>{score.formula}</p><p className="mt-1">Evidence records: {score.evidenceCount}</p></div></details>)}</div></section>
      <section className="grid gap-6 lg:grid-cols-[1fr_1.5fr]"><IssueChart report={report} /><div className="rounded-xl border border-white/[0.07] bg-deepspace p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold text-white">Prioritised recommendations</h2><p className="mt-1 text-xs text-[#4A6280]">Recommendations are linked to issue evidence.</p></div><ArrowRight className="h-4 w-4 text-cyan" /></div><div className="space-y-3">{report.recommendations.length === 0 && <p className="text-sm text-[#7A9AB4]">No recommendations are available from this audit.</p>}{report.recommendations.slice(0, 5).map((item) => <details key={item.id} className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3"><summary className="cursor-pointer list-none"><div className="flex items-start gap-3"><span className={`rounded px-2 py-1 text-[10px] font-bold ${item.priority === 'P0' ? 'bg-red-400/10 text-red-300' : item.priority === 'P1' ? 'bg-amber/10 text-amber' : 'bg-cyan/10 text-cyan'}`}>{item.priority}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium text-white">{item.title}</p><p className="mt-1 text-xs text-[#4A6280]">{item.module} | {item.estimatedTime} | {item.difficulty} effort</p></div><ArrowRight className="h-4 w-4 shrink-0 text-[#4A6280]" /></div></summary><div className="mt-3 border-t border-white/[0.06] pt-3 text-xs leading-5 text-[#94A3B8]"><p>{item.explanation}</p><p className="mt-2 text-cyan">Implementation: {item.implementationGuide}</p><p className="mt-2">Evidence: {item.evidenceIds.join(', ')}</p></div></details>)}</div></div></section>
      <section className="rounded-xl border border-white/[0.07] bg-deepspace p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-white">Evidence provenance</h2><p className="mt-1 text-xs text-[#4A6280]">Raw records used by the report engine.</p></div><button onClick={() => setShowEvidence((value) => !value)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-[#94A3B8] hover:border-cyan/30 hover:text-white">{showEvidence ? 'Hide evidence' : 'View evidence'}</button></div>{showEvidence && <div className="mt-4 max-h-80 space-y-2 overflow-auto">{report.evidence.slice(0, 50).map((item) => <div key={item.id} className="rounded-lg border border-white/[0.05] p-3 text-xs"><div className="flex justify-between gap-3"><span className="font-medium text-cyan">{item.module}</span><span className="text-[#4A6280]">Confidence {Math.round(item.confidence * 100)}%</span></div><p className="mt-1 text-[#94A3B8]">{item.detail}</p><p className="mt-1 text-[#4A6280]">{item.source} | {item.timestamp}</p></div>)}</div>}</section>
      {report.limitations.length > 0 && <section className="rounded-xl border border-amber/20 bg-amber/5 p-4 text-sm text-amber-100"><div className="flex items-center gap-2 font-semibold"><Info className="h-4 w-4" /> Data limits</div>{report.limitations.map((item) => <p key={item} className="mt-1 pl-6 text-xs text-amber-200/80">{item}</p>)}</section>}
      {report.strengths.length > 0 && <section className="rounded-xl border border-teal/20 bg-teal/5 p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-teal"><CheckCircle2 className="h-4 w-4" /> Strengths</div>{report.strengths.map((item) => <p key={item} className="text-xs text-[#94A3B8]">{item}</p>)}</section>}
    </div>}
  </div></main></DashboardLayout>;
}
