import { type Audit, type AuditStatus } from '../../generated';
export type { Audit };
export declare function createAudit(userId: string, domain: string): Promise<Audit>;
export declare function getAuditById(id: string): Promise<Audit | null>;
export declare function getAuditWithResults(id: string): Promise<({
    report: {
        id: string;
        createdAt: Date;
        auditId: string;
        generatedAt: Date;
        expiresAt: Date;
        pdfUrl: string;
    } | null;
    pages: {
        id: string;
        archivedAt: Date | null;
        auditId: string;
        url: string;
        statusCode: number;
        title: string | null;
        metaDescription: string | null;
        h1: string | null;
        canonicalUrl: string | null;
        wordCount: number;
        isIndexable: boolean;
        robotsDirective: string | null;
        internalLinks: number;
        externalLinks: number;
        internalLinksOut: import("../../generated/runtime/library").JsonValue;
        pageRank: number;
        seoScore: number | null;
        seoIssues: import("../../generated/runtime/library").JsonValue;
        aiScore: number | null;
        aiStatus: string;
        schemaData: import("../../generated/runtime/library").JsonValue;
        bodyText: string | null;
        crawledAt: Date;
    }[];
    issues: {
        id: string;
        createdAt: Date;
        type: string;
        auditId: string;
        pageId: string | null;
        pageUrl: string | null;
        module: string;
        severity: import("../../generated").$Enums.IssueSeverity;
        message: string;
        recommendation: string;
        problem: string | null;
        solution: string | null;
        fixCode: string | null;
        fixLanguage: string | null;
    }[];
    scores: {
        id: string;
        createdAt: Date;
        auditId: string;
        seoScore: number;
        aiScore: number;
        overall: number;
        schemaScore: number;
        linkGraphScore: number;
        performanceScore: number;
        breakdown: import("../../generated/runtime/library").JsonValue;
    } | null;
    aiVisibilityScores: {
        id: string;
        createdAt: Date;
        auditId: string;
        breakdown: import("../../generated/runtime/library").JsonValue;
        entityConfidenceScore: number;
        citationProbabilityScore: number;
        aiVisibilityScore: number;
        machineReadabilityScore: number;
        retrievalReadinessScore: number;
        semanticTrustScore: number;
        recommendationConfidence: number;
        providerScores: import("../../generated/runtime/library").JsonValue;
    } | null;
} & {
    id: string;
    userId: string;
    domain: string;
    status: import("../../generated").$Enums.AuditStatus;
    isDemo: boolean;
    startedAt: Date | null;
    completedAt: Date | null;
    errorMessage: string | null;
    pageCount: number | null;
    crawlDurationMs: number | null;
    createdAt: Date;
    updatedAt: Date;
    archivedAt: Date | null;
}) | null>;
export declare function listAuditsByUser(userId: string, page: number, pageSize: number): Promise<{
    data: ({
        scores: {
            id: string;
            createdAt: Date;
            auditId: string;
            seoScore: number;
            aiScore: number;
            overall: number;
            schemaScore: number;
            linkGraphScore: number;
            performanceScore: number;
            breakdown: import("../../generated/runtime/library").JsonValue;
        } | null;
        aiVisibilityScores: {
            id: string;
            createdAt: Date;
            auditId: string;
            breakdown: import("../../generated/runtime/library").JsonValue;
            entityConfidenceScore: number;
            citationProbabilityScore: number;
            aiVisibilityScore: number;
            machineReadabilityScore: number;
            retrievalReadinessScore: number;
            semanticTrustScore: number;
            recommendationConfidence: number;
            providerScores: import("../../generated/runtime/library").JsonValue;
        } | null;
        _count: {
            issues: number;
        };
    } & {
        id: string;
        userId: string;
        domain: string;
        status: import("../../generated").$Enums.AuditStatus;
        isDemo: boolean;
        startedAt: Date | null;
        completedAt: Date | null;
        errorMessage: string | null;
        pageCount: number | null;
        crawlDurationMs: number | null;
        createdAt: Date;
        updatedAt: Date;
        archivedAt: Date | null;
    })[];
    total: number;
}>;
export declare function getAuditsByUser(userId: string, limit?: number): Promise<Audit[]>;
export declare function updateAuditStatus(id: string, status: AuditStatus, metadata?: {
    errorMessage?: string;
    pageCount?: number;
    crawlDurationMs?: number;
}): Promise<void>;
export declare function softDeleteAudit(id: string): Promise<void>;
export declare function getPreviousCompletedAuditIdForDomain(domain: string, excludeAuditId: string): Promise<string | null>;
export declare function countAuditsThisMonth(userId: string): Promise<number>;
export declare function getDemoAudit(domain: string): Promise<({
    report: {
        id: string;
        createdAt: Date;
        auditId: string;
        generatedAt: Date;
        expiresAt: Date;
        pdfUrl: string;
    } | null;
    pages: {
        id: string;
        archivedAt: Date | null;
        auditId: string;
        url: string;
        statusCode: number;
        title: string | null;
        metaDescription: string | null;
        h1: string | null;
        canonicalUrl: string | null;
        wordCount: number;
        isIndexable: boolean;
        robotsDirective: string | null;
        internalLinks: number;
        externalLinks: number;
        internalLinksOut: import("../../generated/runtime/library").JsonValue;
        pageRank: number;
        seoScore: number | null;
        seoIssues: import("../../generated/runtime/library").JsonValue;
        aiScore: number | null;
        aiStatus: string;
        schemaData: import("../../generated/runtime/library").JsonValue;
        bodyText: string | null;
        crawledAt: Date;
    }[];
    issues: {
        id: string;
        createdAt: Date;
        type: string;
        auditId: string;
        pageId: string | null;
        pageUrl: string | null;
        module: string;
        severity: import("../../generated").$Enums.IssueSeverity;
        message: string;
        recommendation: string;
        problem: string | null;
        solution: string | null;
        fixCode: string | null;
        fixLanguage: string | null;
    }[];
    scores: {
        id: string;
        createdAt: Date;
        auditId: string;
        seoScore: number;
        aiScore: number;
        overall: number;
        schemaScore: number;
        linkGraphScore: number;
        performanceScore: number;
        breakdown: import("../../generated/runtime/library").JsonValue;
    } | null;
    aiVisibilityScores: {
        id: string;
        createdAt: Date;
        auditId: string;
        breakdown: import("../../generated/runtime/library").JsonValue;
        entityConfidenceScore: number;
        citationProbabilityScore: number;
        aiVisibilityScore: number;
        machineReadabilityScore: number;
        retrievalReadinessScore: number;
        semanticTrustScore: number;
        recommendationConfidence: number;
        providerScores: import("../../generated/runtime/library").JsonValue;
    } | null;
} & {
    id: string;
    userId: string;
    domain: string;
    status: import("../../generated").$Enums.AuditStatus;
    isDemo: boolean;
    startedAt: Date | null;
    completedAt: Date | null;
    errorMessage: string | null;
    pageCount: number | null;
    crawlDurationMs: number | null;
    createdAt: Date;
    updatedAt: Date;
    archivedAt: Date | null;
}) | null>;
export declare function listDemoAudits(): Promise<{
    id: string;
    domain: string;
    completedAt: Date | null;
    pageCount: number | null;
}[]>;
//# sourceMappingURL=audits.d.ts.map