import { createConfidenceSummary, type AuditCoverage, type EvidenceProjection, type EvidenceProjectionConfidence, type EvidenceScope, type IntelligenceReportVersionMetadata, type VerificationState } from './intelligence-report-v2';
import type { IntelligenceReportV2Input, IntelligenceReportV2InputValidation } from './intelligence-report-v2-input';
import type { IntelligenceModuleExecutionSummary, ProviderAvailability } from './intelligence-module-state';
import type { RawRenderedEvidenceComparison } from './raw-rendered-evidence-projection';
import type { EvidenceContradiction } from './evidence-contradictions';
import type { RootCauseGroup } from './root-cause-grouping';
import type { FindingEligibilityResult } from './finding-integrity';

export const CANONICAL_REPORT_STATES = ['READY', 'PARTIAL', 'LIMITED', 'INVALID'] as const;
export type CanonicalReportState = (typeof CANONICAL_REPORT_STATES)[number];
export const CANONICAL_SCORE_STATES = ['NOT_CALCULATED', 'CALCULATED', 'UNAVAILABLE'] as const;
export type CanonicalScoreState = (typeof CANONICAL_SCORE_STATES)[number];

export interface CanonicalReportIdentity { reportId: string; auditId: string; domain: string; projectId?: string | null | undefined; tenantId?: string | null | undefined; organizationId?: string | null | undefined; reportVersion: string; evidenceModelVersion: string; scoringModelVersion: string; crawlerVersion: string; generatedAt?: string | null | undefined; assemblerVersion?: string | null | undefined; }
export interface CanonicalAuditContext { auditStartedAt?: string | null | undefined; auditCompletedAt?: string | null | undefined; executionMode?: string | undefined; auditLayer?: string | null | undefined; sourceAuditVersion?: string | null | undefined; classification: 'CURRENT' | 'HISTORICAL'; }
export interface CanonicalBusinessContext { organizationName?: string | null; primaryCategory?: string | null; secondaryCategories?: string[]; classificationConfidence?: EvidenceProjectionConfidence; commercialRiskClassification?: string | null; }
export interface CanonicalReportFinding { id: string; auditId?: string | undefined; sourceIssueId?: string | undefined; sourcePageId?: string | undefined; sourceIssueType?: string | undefined; ruleId?: string | null | undefined; moduleId?: string | null | undefined; title: string; description?: string | null | undefined; scope: EvidenceScope; verificationState: VerificationState; severity?: EvidenceProjection['severity']; confidence: EvidenceProjectionConfidence; affectedUrls: string[]; evidenceIds: string[]; contradictionIds: string[]; rootCauseIds: string[]; unresolved?: boolean; metadata?: Record<string, string | number | boolean | null>; }
/** `trace` is the full Phase 15 `ScoringV2CategoryTrace` for this category, kept as `unknown` here to avoid a circular import into the scoring engine; the "Why This Score" view-model in apps/web narrows it with a runtime guard before use. */
export interface CanonicalScoreMetadata { status: string; diagnostics: string; trace: unknown; }
export interface CanonicalScorePlaceholder { category: string; state: CanonicalScoreState; score?: number; weight?: number; weightedContribution?: number; confidence?: EvidenceProjectionConfidence; coverage?: number; methodologyVersion?: string; positiveContributors: string[]; negativeContributors: string[]; rootCauseIds: string[]; contradictionIds: string[]; evidenceIds: string[]; unavailableReason?: string; metadata?: CanonicalScoreMetadata; }
export interface CanonicalRecommendationPlaceholder { id: string; title: string; findingIds: string[]; rootCauseIds: string[]; evidenceIds: string[]; affectedUrls: string[]; priority?: string; owner?: string; effort?: string; validation?: string; status?: string; }
export interface CanonicalOpportunityPlaceholder { id: string; type: string; title: string; evidenceIds: string[]; expectedImpact?: string; confidence?: EvidenceProjectionConfidence; categories: string[]; }
export interface ReportLimitation { code: string; title: string; description?: string | undefined; relatedModuleId?: string; relatedProvider?: string; evidenceIds: string[]; severity?: CanonicalReportFinding['severity']; metadata?: Record<string, string | number | boolean | null>; }
export interface CanonicalHistoricalPlaceholder { available: boolean; comparable: boolean; reason?: string; sourceAuditIds: string[]; evidence: EvidenceProjection[]; }
export interface CanonicalReportMetadata { assembledAt?: string | null | undefined; assemblerVersion?: string | null | undefined; inputValidation: IntelligenceReportV2InputValidation; warnings: string[]; }
export interface CanonicalIntelligenceReportV2 { identity: CanonicalReportIdentity; methodology: IntelligenceReportVersionMetadata; audit: CanonicalAuditContext; business?: CanonicalBusinessContext; coverage?: AuditCoverage; confidence: EvidenceProjectionConfidence; moduleStatus: IntelligenceModuleExecutionSummary[]; providers: ProviderAvailability[]; evidence: EvidenceProjection[]; rawRenderedComparisons: RawRenderedEvidenceComparison[]; findings: CanonicalReportFinding[]; contradictions: EvidenceContradiction[]; rootCauses: RootCauseGroup[]; scores: CanonicalScorePlaceholder[]; legacyScores: Record<string, number | null>; recommendations: CanonicalRecommendationPlaceholder[]; opportunities: CanonicalOpportunityPlaceholder[]; limitations: ReportLimitation[]; historical: CanonicalHistoricalPlaceholder; metadata: CanonicalReportMetadata; state: CanonicalReportState; }

export interface CanonicalProjectionFinding { id: string; title: string; scope: EvidenceScope; requestedVerificationState?: VerificationState; eligibility: FindingEligibilityResult; ruleId?: string | null | undefined; moduleId?: string | null | undefined; description?: string | null | undefined; severity?: CanonicalReportFinding['severity']; }
export interface CanonicalIntelligenceReportV2ProjectionInput { input: IntelligenceReportV2Input; validation: IntelligenceReportV2InputValidation; findings?: readonly CanonicalProjectionFinding[]; contradictions?: readonly EvidenceContradiction[]; rootCauses?: readonly RootCauseGroup[]; scores?: readonly CanonicalScorePlaceholder[]; legacyScores?: Readonly<Record<string, number | null>>; recommendations?: readonly CanonicalRecommendationPlaceholder[]; opportunities?: readonly CanonicalOpportunityPlaceholder[]; business?: CanonicalBusinessContext; reportId?: string; assembledAt?: string; assemblerVersion?: string; }

/** Pure projection. It does not query, crawl, score, persist, or generate prose. */
export function projectCanonicalIntelligenceReportV2(request: CanonicalIntelligenceReportV2ProjectionInput): CanonicalIntelligenceReportV2 {
  const source = request.input;
  const findings = (request.findings ?? []).map(projectFinding);
  const limitations = deriveLimitations(source, request.scores ?? []);
  const state = reportState(request.validation, limitations, source.coverage);
  const historical = { available: (source.historicalEvidence?.length ?? 0) > 0, comparable: false, ...(source.historicalEvidence?.length ? { reason: 'Historical evidence is supplied but no comparison was performed.' } : { reason: 'Historical comparison was not supplied.' }), sourceAuditIds: unique(source.historicalEvidence?.map((item) => item.auditId) ?? []), evidence: [...(source.historicalEvidence ?? [])] };
  return {
    identity: { reportId: request.reportId ?? `report-v2:${source.audit.auditId}`, auditId: source.audit.auditId, domain: source.audit.domain, projectId: source.audit.projectId, tenantId: source.audit.tenantId, organizationId: source.audit.organizationId, reportVersion: source.version.reportVersion, evidenceModelVersion: source.version.evidenceModelVersion, scoringModelVersion: source.version.scoringModelVersion, crawlerVersion: source.version.crawlerVersion, generatedAt: request.assembledAt ?? source.metadata?.assembledAt, assemblerVersion: request.assemblerVersion ?? source.metadata?.assemblerVersion },
    methodology: { ...source.version }, audit: { auditStartedAt: source.audit.auditStartedAt, auditCompletedAt: source.audit.auditCompletedAt, executionMode: source.audit.auditExecutionMode, auditLayer: source.audit.auditLayer, sourceAuditVersion: source.metadata?.sourceAuditVersion, classification: 'CURRENT' }, ...(request.business ? { business: copyBusiness(request.business) } : {}), ...(source.coverage ? { coverage: copyCoverage(source.coverage) } : {}), confidence: copyConfidence(source.confidence), moduleStatus: source.modules.map(copyModule), providers: source.providers.map((provider) => ({ ...provider })), evidence: [...source.evidence], rawRenderedComparisons: [...source.rawRenderedComparisons], findings, contradictions: [...(request.contradictions ?? [])], rootCauses: [...(request.rootCauses ?? [])], scores: request.scores ? request.scores.map(copyScore) : [notCalculatedScore()], legacyScores: { ...(request.legacyScores ?? {}) }, recommendations: [...(request.recommendations ?? [])], opportunities: [...(request.opportunities ?? [])], limitations, historical, metadata: { assembledAt: request.assembledAt ?? source.metadata?.assembledAt, assemblerVersion: request.assemblerVersion ?? source.metadata?.assemblerVersion, inputValidation: copyValidation(request.validation), warnings: [...request.validation.warnings.map((item) => item.message)] }, state,
  };
}
function projectFinding(source: CanonicalProjectionFinding): CanonicalReportFinding { const requested = source.requestedVerificationState ?? 'CONFIRMED'; const supported = source.eligibility.maximumVerificationState; const rank = (state: VerificationState) => ({ CONFIRMED: 5, LIKELY: 4, PARTIAL: 3, INFERRED: 3, UNVERIFIED: 2, CONFLICTING: 2, NOT_DETECTED: 2, NOT_APPLICABLE: 2, CRAWL_FAILED: 1, TEMPORARY_FAILURE: 1, RENDERING_REQUIRED: 2, EXTERNAL_DATA_REQUIRED: 2, PROVIDER_UNAVAILABLE: 1 } as const)[state]; const state = source.eligibility.eligible && rank(supported) >= rank(requested) ? requested : supported; return { id: source.id, ruleId: source.ruleId, moduleId: source.moduleId, title: source.title, description: source.description, scope: source.scope, verificationState: state, severity: source.severity, confidence: createConfidenceSummary({ reasons: source.eligibility.diagnostics.map((item) => item.message) }), affectedUrls: [...source.eligibility.affectedUrls], evidenceIds: [...source.eligibility.evidenceIds], contradictionIds: [], rootCauseIds: [], unresolved: !source.eligibility.eligible }; }
function deriveLimitations(input: IntelligenceReportV2Input, scores: readonly CanonicalScorePlaceholder[]): ReportLimitation[] { const output: ReportLimitation[] = []; for (const provider of input.providers) if (!provider.available) output.push({ code: 'PROVIDER_UNAVAILABLE', title: `${provider.provider} is unavailable`, description: provider.reason, relatedProvider: provider.provider, evidenceIds: [] }); for (const module of input.modules) if (module.state === 'PARTIAL' || module.state === 'UNAVAILABLE' || module.state === 'BLOCKED') output.push({ code: `MODULE_${module.state}`, title: `${module.moduleId} is ${module.state.toLowerCase()}`, description: module.reason, relatedModuleId: module.moduleId, evidenceIds: [] }); if (input.coverage && input.coverage.coverageRatio !== undefined && input.coverage.coverageRatio < 1) output.push({ code: 'PARTIAL_CRAWL_COVERAGE', title: 'Crawl coverage is partial', description: 'Observed coverage is below complete coverage.', evidenceIds: [] }); if (!scores.some((score) => score.state === 'CALCULATED')) output.push({ code: 'SCORING_V2_NOT_CALCULATED', title: 'Scoring v2 is not calculated', evidenceIds: [] }); return output; }
function reportState(validation: IntelligenceReportV2InputValidation, limitations: readonly ReportLimitation[], coverage: AuditCoverage | undefined): CanonicalReportState { if (!validation.valid) return 'INVALID'; if (limitations.some((item) => item.code === 'PROVIDER_UNAVAILABLE') || (coverage?.coverageRatio !== undefined && coverage.coverageRatio < 0.5)) return 'LIMITED'; return limitations.length > 0 ? 'PARTIAL' : 'READY'; }
function notCalculatedScore(): CanonicalScorePlaceholder { return { category: 'Intelligence Report v2', state: 'NOT_CALCULATED', positiveContributors: [], negativeContributors: [], rootCauseIds: [], contradictionIds: [], evidenceIds: [], unavailableReason: 'Scoring v2 is not calculated in this projection phase.' }; }
function copyConfidence(value: EvidenceProjectionConfidence): EvidenceProjectionConfidence { return { ...value, reasons: [...value.reasons] }; } function copyModule(value: IntelligenceModuleExecutionSummary): IntelligenceModuleExecutionSummary { return { ...value, ...(value.metadata ? { metadata: { ...value.metadata } } : {}) }; } function copyCoverage(value: AuditCoverage): AuditCoverage { return { ...value, providersAvailable: [...value.providersAvailable], providersUnavailable: [...value.providersUnavailable] }; } function copyBusiness(value: CanonicalBusinessContext): CanonicalBusinessContext { return { ...value, ...(value.secondaryCategories ? { secondaryCategories: [...value.secondaryCategories] } : {}), ...(value.classificationConfidence ? { classificationConfidence: copyConfidence(value.classificationConfidence) } : {}) }; } function copyScore(value: CanonicalScorePlaceholder): CanonicalScorePlaceholder { return { ...value, positiveContributors: [...value.positiveContributors], negativeContributors: [...value.negativeContributors], rootCauseIds: [...value.rootCauseIds], contradictionIds: [...value.contradictionIds], evidenceIds: [...value.evidenceIds], ...(value.confidence ? { confidence: copyConfidence(value.confidence) } : {}) }; } function copyValidation(value: IntelligenceReportV2InputValidation): IntelligenceReportV2InputValidation { return { valid: value.valid, warnings: value.warnings.map((item) => ({ ...item })), errors: value.errors.map((item) => ({ ...item })) }; } function unique(values: readonly string[]): string[] { return [...new Set(values.filter(Boolean))]; }