import { describe, expect, it } from 'vitest';
import { createConfidenceSummary, projectCanonicalReportFindings, type EvidenceProjection } from '@sitenexis/shared';
const issue={id:'i1',auditId:'a1',pageId:'p1',pageUrl:'https://example.com/page',module:'seo',type:'MISSING_H1',severity:'high',message:'Missing H1',recommendation:'Add a real H1',problem:'No H1 observed'};
const evidence:EvidenceProjection={id:'e1',auditId:'a1',domain:'example.com',scope:'PAGE',category:'seo',title:'H1',description:'x',confidence:createConfidenceSummary({score:.9}),verificationState:'CONFIRMED',issueId:'i1',url:'https://example.com/page'};
const confirmed={eligible:true,maximumVerificationState:'CONFIRMED' as const,diagnostics:[],evidenceIds:['e1'],affectedUrls:['https://example.com/page']};
describe('canonical finding projection',()=>{
 it('preserves strong legacy issue linkage and evidence',()=>{const r=projectCanonicalReportFindings({auditId:'a1',legacyIssues:[issue],evidence:[evidence],eligibilityByIssueId:{i1:confirmed}});expect(r.findings[0]).toMatchObject({id:'canonical-finding:a1:i1',sourceIssueId:'i1',sourcePageId:'p1',verificationState:'CONFIRMED',severity:'high',evidenceIds:['e1'],affectedUrls:['https://example.com/page']});});
 it('caps unsupported raw/rendered page findings and retains them unresolved',()=>{const r=projectCanonicalReportFindings({auditId:'a1',legacyIssues:[issue],eligibilityByIssueId:{i1:{...confirmed,eligible:false,maximumVerificationState:'PARTIAL'}}});expect(r.findings[0]).toMatchObject({verificationState:'PARTIAL',unresolved:true});expect(r.diagnostics[0]?.code).toBe('CAPPED_VERIFICATION_STATE');});
 it('keeps no-evidence legacy items cautious, blocks historical mixing, and deduplicates source issues',()=>{const before=JSON.stringify(issue);const r=projectCanonicalReportFindings({auditId:'a1',legacyIssues:[{id:'i2',auditId:'a1',pageId:'p1',module:'seo',type:'MISSING_H1',severity:'high',message:'Missing H1',recommendation:'Add a real H1',problem:'No H1 observed'}, {id:'i2',auditId:'a1',pageId:'p1',module:'seo',type:'MISSING_H1',severity:'high',message:'Missing H1',recommendation:'Add a real H1',problem:'No H1 observed'},{...issue,id:'old',auditId:'old'}]});expect(r.findings).toHaveLength(1);expect(r.findings[0]).toMatchObject({verificationState:'UNVERIFIED',unresolved:true});expect(r.diagnostics.map(x=>x.code)).toEqual(expect.arrayContaining(['MISSING_ELIGIBILITY','HISTORICAL_ISSUE_EXCLUDED']));expect(JSON.stringify(issue)).toBe(before);});
 it('links contradictions and root causes without changing severity or creating recommendations',()=>{const r=projectCanonicalReportFindings({auditId:'a1',legacyIssues:[issue],evidence:[evidence],eligibilityByIssueId:{i1:confirmed},contradictions:[{id:'c1',type:'CANONICAL_CONFLICT',subject:'page.canonical',scope:'PAGE',severity:'high',confidence:createConfidenceSummary(),evidenceIds:['e1'],values:[],affectedUrls:[],modules:[],reason:'x',resolutionStatus:'UNRESOLVED'}],rootCauses:[{id:'r1',type:'CANONICAL_CONFIGURATION_CONFLICT',subject:'page:x:canonical',scope:'PAGE',title:'x',evidenceIds:['e1'],contradictionIds:['c1'],findingCandidateIds:[],affectedUrls:[],modules:[],primaryCategory:'Technical SEO',secondaryCategories:[],confidence:createConfidenceSummary(),severity:'high',groupingReason:'x'}]});expect(r.findings[0]).toMatchObject({severity:'high',contradictionIds:['c1'],rootCauseIds:['r1']});expect(r.findings[0]?.metadata?.legacyRecommendation).toBe('Add a real H1');});
});