import { describe, expect, it } from 'vitest';
import { createConfidenceSummary, projectCanonicalIntelligenceReportV2, type IntelligenceReportV2Input } from '@sitenexis/shared';
function input(): IntelligenceReportV2Input { return { audit:{auditId:'a1',domain:'example.com'},version:{scoringModelVersion:'v2',reportVersion:'v2',evidenceModelVersion:'v2',crawlerVersion:'v2'},evidence:[],rawRenderedComparisons:[],modules:[],providers:[],confidence:createConfidenceSummary()}; }
const validation={valid:true,warnings:[],errors:[]};
describe('canonical intelligence report v2 projection',()=>{
 it('projects a minimal report without defaulting v2 scores to zero',()=>{const report=projectCanonicalIntelligenceReportV2({input:input(),validation}); expect(report).toMatchObject({state:'PARTIAL',confidence:{label:'UNKNOWN'}}); expect(report.scores[0]).toMatchObject({state:'NOT_CALCULATED'}); expect(report.scores[0]?.score).toBeUndefined();});
 it('carries rich normalized inputs and keeps contradictions/root causes distinct',()=>{const source=input(); source.evidence=[{id:'e1',auditId:'a1',domain:'example.com',scope:'PAGE',category:'seo',title:'H1',description:'x',confidence:createConfidenceSummary({score:.9}),verificationState:'CONFIRMED',url:'https://example.com/p'}]; source.modules=[{moduleId:'scout',state:'COMPLETED'}]; source.providers=[{provider:'serp',available:true}]; const report=projectCanonicalIntelligenceReportV2({input:source,validation,contradictions:[{id:'c1',type:'H1_CONFLICT',subject:'page.h1',scope:'PAGE',severity:'low',confidence:createConfidenceSummary({score:.8}),evidenceIds:['e1'],values:[],affectedUrls:['https://example.com/p'],modules:[],reason:'x',resolutionStatus:'UNRESOLVED'}],rootCauses:[{id:'r1',type:'RENDERING_DEPENDENCY',subject:'page:p:rendering',scope:'PAGE',title:'Rendering',evidenceIds:['e1'],contradictionIds:['c1'],findingCandidateIds:[],affectedUrls:['https://example.com/p'],modules:[],primaryCategory:'Web Health and Crawlability',secondaryCategories:[],confidence:createConfidenceSummary({score:.8}),severity:'medium',groupingReason:'x'}],legacyScores:{health:75}}); expect(report.evidence).toHaveLength(1);expect(report.contradictions).toHaveLength(1);expect(report.rootCauses).toHaveLength(1);expect(report.legacyScores).toEqual({health:75});});
 it('caps unsupported confirmed findings and derives deterministic limitations',()=>{const source=input();source.providers=[{provider:'backlinks',available:false,reason:'Missing credential'}];source.modules=[{moduleId:'scout',state:'PARTIAL',partial:true}];source.coverage={discoveredUrls:2,attemptedUrls:2,successfulUrls:1,renderedUrls:0,partialUrls:0,failedUrls:1,blockedUrls:0,redirectedUrls:0,excludedUrls:0,externalSourcesChecked:0,providersAvailable:[],providersUnavailable:['backlinks'],coverageRatio:.5};const report=projectCanonicalIntelligenceReportV2({input:source,validation,findings:[{id:'f1',title:'Missing H1',scope:'PAGE',eligibility:{eligible:false,maximumVerificationState:'PARTIAL',diagnostics:[],evidenceIds:[],affectedUrls:[]} }]});expect(report.findings[0]).toMatchObject({verificationState:'PARTIAL',unresolved:true});expect(report.limitations.map(x=>x.code)).toEqual(expect.arrayContaining(['PROVIDER_UNAVAILABLE','MODULE_PARTIAL','PARTIAL_CRAWL_COVERAGE','SCORING_V2_NOT_CALCULATED']));expect(report.state).toBe('LIMITED');});
 it('marks fatal composition validation invalid and keeps history separate and input immutable',()=>{const source=input();source.historicalEvidence=[{id:'old',auditId:'a0',domain:'example.com',scope:'PAGE',category:'x',title:'old',description:'x',confidence:createConfidenceSummary(),verificationState:'CONFIRMED'}];const bad={valid:false,warnings:[{code:'DOMAIN_MISMATCH' as const,message:'warn'}],errors:[{code:'CROSS_AUDIT_EVIDENCE' as const,message:'bad'}]};const before=JSON.stringify(source);const one=projectCanonicalIntelligenceReportV2({input:source,validation:bad});const two=projectCanonicalIntelligenceReportV2({input:source,validation:bad});expect(one.state).toBe('INVALID');expect(one.historical).toMatchObject({available:true,comparable:false});expect(one).toEqual(two);expect(JSON.stringify(source)).toBe(before);});
});