export type ContentBlock =
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'p'; text: string }
  | { type: 'list'; ordered?: boolean; items: string[] }
  | { type: 'callout'; variant: 'info' | 'tip' | 'warning'; text: string }

export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  category: string
  publishedAt: string
  readTime: number
  tags: string[]
  content: ContentBlock[]
}

export const CATEGORIES = ['All', 'AI Visibility', 'Machine Trust', 'Entity SEO', 'Technical SEO', 'Strategy'] as const

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'why-ai-systems-ignore-70-percent-of-your-content',
    title: 'Why AI Systems Ignore 70% of Your Content (And What to Do About It)',
    excerpt: 'AI systems don\'t read pages — they process chunks. Understanding this distinction is the foundation of modern SEO.',
    category: 'AI Visibility',
    publishedAt: 'May 29, 2025',
    readTime: 6,
    tags: ['AI SEO', 'Machine Readability', 'Chunking', 'Content Strategy'],
    content: [
      { type: 'p', text: 'Every second, millions of web pages are being processed by AI retrieval systems — and most of those pages are losing the majority of their content in the process. Navigation menus, footers, cookie banners, boilerplate sidebars: all stripped out before the AI ever encounters your actual message. What remains is a fraction of what you wrote, broken into discrete units of roughly 300–600 tokens each. This is the reality of AI content consumption, and most websites are not built for it.' },
      { type: 'h2', text: 'The AI Retrieval Pipeline' },
      { type: 'p', text: 'When an AI system encounters your website, it runs content through a deterministic extraction pipeline. Raw HTML is rendered, then stripped of navigation and structural chrome. The remaining text is split into semantic chunks — discrete units that can be independently retrieved and embedded. Each chunk is converted into a vector representation and scored for relevance against incoming queries. Only the highest-scoring chunks reach the summarization and citation stage, where they become part of an AI-generated response.' },
      { type: 'p', text: 'The failure points are everywhere: chunks that split mid-sentence due to poor paragraph structure, boilerplate that inflates the noise-to-signal ratio, entities that are never explicitly defined, and claims that require context from three other paragraphs to be coherent. At each failure point, your content loses ground to sources that are structured for machine consumption.' },
      { type: 'h2', text: 'What Gets Filtered Out' },
      { type: 'list', items: [
        'Navigation menus and site chrome — removed entirely before chunking',
        'Footer content, sidebar widgets, cookie consent blocks',
        'Decorative or redundant text that appears on every page',
        'Chunks where semantic meaning requires cross-chunk context',
        'Claims without entity attribution or factual grounding',
        'Content positioned past the context window limit on long pages',
      ]},
      { type: 'h2', text: 'What AI Systems Actually Consume' },
      { type: 'p', text: 'AI retrieval systems are optimized to consume named entities, factual claims, structured summaries, and direct answers to anticipated queries. A chunk that opens with a clear entity definition, contains specific verifiable claims, and ends with a coherent conclusion will outperform a chunk that meanders through qualifications and calls to action. The AI does not care about your brand voice. It cares about information density.' },
      { type: 'callout', variant: 'tip', text: 'Run a boilerplate ratio test on your top pages. If more than 40% of extracted text is navigation, footers, or repeated site chrome, your machine readability score is almost certainly below 60.' },
      { type: 'h2', text: 'How to Fix It' },
      { type: 'list', ordered: true, items: [
        'Structure each paragraph as a self-contained semantic unit — avoid dangling references that require prior context',
        'Define your primary entity explicitly on every key page, not just the About page',
        'Use heading hierarchy (H1→H2→H3) to align with content depth, not visual styling',
        'Place your most retrievable claims in the first 200 words of each page section',
        'Minimize boilerplate by using template-separated navigation and footer content',
      ]},
    ],
  },
  {
    slug: 'entity-optimization-the-signal-ai-systems-weight-most',
    title: 'Entity Optimization: The Signal AI Systems Weight Most',
    excerpt: 'Entities are the atomic units of AI knowledge. If your primary entity is inconsistent or undefined, AI visibility is impossible — regardless of technical SEO health.',
    category: 'Entity SEO',
    publishedAt: 'May 27, 2025',
    readTime: 7,
    tags: ['Entity SEO', 'Knowledge Graph', 'Entity Intelligence', 'AI Search'],
    content: [
      { type: 'p', text: 'In the knowledge graph model that underlies AI retrieval, entities are not an SEO tactic — they are the fundamental unit of information. An entity is a named, stable, real-world object with consistent, unambiguous attributes: a company, a person, a product, a place, a concept. When an AI system extracts meaning from your website, it is not parsing keywords — it is identifying entities, mapping their relationships, and scoring their consistency. If your primary entity is poorly defined, inconsistently described, or absent from key pages, the AI\'s model of your site is built on sand.' },
      { type: 'h2', text: 'What Is an Entity in AI Terms?' },
      { type: 'p', text: 'An entity exists at the intersection of three properties: it has a name (consistent across all surfaces), a type (Organisation, Person, Product, Place), and a set of attributes that remain stable across independent sources. The stability requirement is what differentiates entity-based trust from traditional authority signals. A site can have high domain authority while having completely inconsistent entity data — and an AI system will down-weight its content accordingly.' },
      { type: 'h2', text: 'The Entity Confidence Score' },
      { type: 'p', text: 'Entity Confidence is a composite of four dimensions: detection rate (are entities named explicitly on every relevant page?), consistency score (do entity attributes match across schema, body text, and metadata?), coverage score (is the entity described with sufficient attribute depth?), and disambiguation score (is this entity clearly distinct from others with similar names?). A low score in any dimension creates a credibility gap that AI systems penalize.' },
      { type: 'h2', text: 'Common Entity Failures' },
      { type: 'list', items: [
        'Primary entity (the organisation or brand) not explicitly defined on key pages',
        'Founding year or location described differently on different pages',
        'Schema name attribute conflicting with the name used in body text',
        'No sameAs links to Wikipedia, Wikidata, LinkedIn, or Companies House',
        'Author entities referenced in schema but not mentioned in article body',
        'Product entities with conflicting descriptions across landing pages and blog content',
      ]},
      { type: 'callout', variant: 'warning', text: 'If your schema name attribute and H1 heading do not exactly match the entity name used throughout your site\'s body text, you have an entity consistency failure. This is one of the most common and highest-impact issues in AI visibility audits.' },
      { type: 'h2', text: 'Entity Optimization Tactics' },
      { type: 'list', ordered: true, items: [
        'Create a canonical entity definition page — your About or Company page should function as the authoritative entity description',
        'Use Organization schema with name, url, description, foundingDate, sameAs, and logo consistently across every page',
        'Add sameAs links to at least three authoritative external sources that confirm your entity attributes',
        'Audit all pages where your primary entity is mentioned — check that name, description, and type are consistent',
        'For person entities (authors, founders), implement Person schema and link to their external profiles',
      ]},
    ],
  },
  {
    slug: 'schema-markup-ai-trust-signals-2025',
    title: 'Schema Markup in 2025: From SEO Signals to AI Trust Infrastructure',
    excerpt: 'Schema is no longer just about rich results. In the age of AI retrieval, structured data is the foundation of machine trust — and most implementations are getting it wrong.',
    category: 'Technical SEO',
    publishedAt: 'May 24, 2025',
    readTime: 5,
    tags: ['Schema Markup', 'Structured Data', 'Machine Trust', 'Technical SEO'],
    content: [
      { type: 'p', text: 'When schema markup was first introduced, the goal was simple: help search engines understand page content to generate rich results. In 2025, that goal has expanded dramatically. Schema is now the primary channel through which AI systems validate entity claims, verify source credibility, and determine whether your content passes the trust threshold required to appear in AI-generated responses. Most implementations optimized for the 2018 rich results landscape are actively undermining machine trust today.' },
      { type: 'h2', text: 'Schema as Machine Trust Infrastructure' },
      { type: 'p', text: 'AI systems use schema markup to cross-reference claims made in body text. When your Organization schema states you were founded in 2012, and your About page body text says "established over a decade ago," those signals are consistent. When your Article schema attributes authorship to "Content Team" while the byline says "Sarah Johnson," those signals contradict. Every contradiction is a trust penalty. AI systems do not award partial credit for partial consistency.' },
      { type: 'h2', text: 'The Trust Alignment Problem' },
      { type: 'p', text: 'The most pervasive schema error in modern implementations is over-claiming: adding schema attributes that are not evidenced in the page body. An AggregateRating schema block with a 4.8 score on a page that contains no visible reviews is not just an SEO risk — it is an active trust violation. AI systems cross-reference schema claims against body content. Claims present only in schema receive a validation penalty. The schema must describe the page, not inflate it.' },
      { type: 'callout', variant: 'warning', text: 'Every schema claim must be verifiable from the page body. If your schema includes attributes that do not appear in your visible content, you are creating schema-to-content contradictions that degrade machine trust scores.' },
      { type: 'h2', text: 'Essential Schema for AI Visibility' },
      { type: 'list', items: [
        'Organization: name, url, description, foundingDate, logo, sameAs — identical across all pages',
        'Article / BlogPosting: author with @type Person, datePublished, dateModified, headline matching H1',
        'BreadcrumbList: accurate path from homepage to current page',
        'FAQPage: question and acceptedAnswer pairs that match verbatim body text',
        'HowTo: orderedStep elements with exact step names from body content',
        'SpeakableSpecification: on pages with short, directly retrievable factual claims',
      ]},
      { type: 'h2', text: 'Schema Anti-Patterns to Eliminate' },
      { type: 'list', items: [
        'AggregateRating without visible review content on the same page',
        'datePublished set to the site launch date instead of the actual publish date',
        'Author schema for entities not named in body text',
        'SchemaType that does not match actual page content category',
        'Speakable markup on pages without concise, directly retrievable answers',
      ]},
    ],
  },
  {
    slug: 'machine-trust-score-replacing-domain-authority',
    title: 'What Is Machine Trust Score and Why It\'s Replacing Domain Authority',
    excerpt: 'Domain Authority was a proxy for link equity. Machine Trust Score measures something entirely different — and more important for AI-driven search.',
    category: 'Machine Trust',
    publishedAt: 'May 22, 2025',
    readTime: 8,
    tags: ['Machine Trust', 'Domain Authority', 'AI Search', 'Trust Signals'],
    content: [
      { type: 'p', text: 'Domain Authority, as a metric, models the link equity flowing through a domain — a proxy for how much trust the web\'s link graph assigns to a source. For years, this was a reasonable approximation of search authority. But AI retrieval systems do not operate on link graphs. They operate on information graphs: networks of entities, claims, and validation signals. In this model, a site with Domain Authority 85 but inconsistent entity data and contradictory schema will underperform a site with DA 40 that has impeccable information consistency.' },
      { type: 'h2', text: 'How AI Systems Form Trust' },
      { type: 'p', text: 'Trust in AI systems is a composite formed from cross-source validation, entity consistency, internal coherence, and the absence of contradictory claims. It is not formed from a single signal — it is accumulated through the convergence of many signals across many pages over time. A single contradiction on a high-value page can undermine the trust accumulated by dozens of well-optimized pages. Trust is asymmetric: easy to lose, slow to rebuild.' },
      { type: 'h2', text: 'The Five Components of Machine Trust' },
      { type: 'list', ordered: true, items: [
        'Entity Credibility Consistency (30%): Entity attributes consistent across all pages, schema, and external sources',
        'Schema Trust Alignment (20%): Schema markup accurately describes page content without over-claiming',
        'External Validation Depth (25%): sameAs links resolve to expected entities with confirmed attributes',
        'Contradiction Absence Score (15%): No factual conflicts between pages or between schema and body text',
        'Trust Degradation Resistance (10%): No signs of previous trust signals being removed or changed',
      ]},
      { type: 'h2', text: 'Trust vs. Authority: The Key Difference' },
      { type: 'p', text: 'Authority, in the traditional SEO sense, flows from external links. A single high-authority backlink can significantly move Domain Authority. Machine Trust cannot be acquired this way. It is built from the inside out — from the quality and consistency of information on your own domain. No external link can compensate for contradictory entity data or schema that misrepresents your content. This fundamentally changes the optimization calculus for AI visibility.' },
      { type: 'callout', variant: 'info', text: 'Machine Trust is measured per-domain, not per-page. Inconsistent data on a single important page can drag down the trust score for your entire domain, not just that page.' },
      { type: 'h2', text: 'Building Machine Trust' },
      { type: 'list', ordered: true, items: [
        'Audit all pages where your primary entity is described — ensure zero attribute conflicts',
        'Add sameAs links to authoritative external sources that validate your entity claims',
        'Review schema markup across your entire domain for over-claiming and type mismatches',
        'Implement a content review process that flags entity attribute changes',
        'Add dateModified schema to all important pages and update it when content changes',
      ]},
    ],
  },
  {
    slug: 'how-to-increase-citation-probability-ai-search',
    title: 'How to Increase Your Citation Probability in AI Search Results',
    excerpt: 'Being cited by an AI system is the new high-value link. Citation probability is measurable, improvable, and has a direct impact on your AI visibility.',
    category: 'AI Visibility',
    publishedAt: 'May 20, 2025',
    readTime: 6,
    tags: ['Citation Probability', 'AI Citations', 'Content Strategy', 'AI Visibility'],
    content: [
      { type: 'p', text: 'When an AI system generates a response and cites your page, you gain a form of visibility that no traditional SEO metric captures: your content becomes the source for an AI-generated answer that may be seen by thousands of users without a single click on your link. Citation probability — the likelihood that an AI system selects your content as a source — is now one of the most consequential performance metrics in digital marketing. It is also one of the most improvable.' },
      { type: 'h2', text: 'What Makes Content Citation-Worthy' },
      { type: 'p', text: 'AI systems select citations based on a combination of factors that differ significantly from traditional ranking signals. Link count and Domain Authority play a secondary role. What AI systems primarily weight are the precision and density of factual claims, the depth of topical authority on the subject, and the structural characteristics that make content directly quotable.' },
      { type: 'list', items: [
        'Factual density: the ratio of specific, verifiable claims to total content length',
        'Claim specificity: named entities, specific dates, specific statistics rather than general assertions',
        'Primary entity authority: the site\'s expertise and coverage depth on the entity being queried',
        'Topical authority depth: multiple pages covering related sub-topics, not just the query topic',
        'Structural citation readiness: content formatted as discrete, directly quotable claims',
        'Temporal freshness: recency of the content and recency of the underlying facts',
      ]},
      { type: 'h2', text: 'High-Citation Content Patterns' },
      { type: 'p', text: 'The content that AI systems cite most frequently shares identifiable structural patterns. It contains specific statistics with named sources. It makes definitive claims using the form "[Entity] [verb] [specific attribute]." It uses FAQ-style question-and-answer structures that align with query patterns. It defines terms clearly on first use and maintains those definitions throughout. It avoids hedging language that reduces the specificity of claims.' },
      { type: 'callout', variant: 'tip', text: 'Write your key claims in the form of a direct, verifiable statement: "SiteNexis detects synthetic entity patterns using five signal categories, including network integrity analysis." This is more citable than: "SiteNexis uses advanced AI to help understand your domain\'s entity structure."' },
      { type: 'h2', text: 'What Kills Citation Probability' },
      { type: 'list', items: [
        'Vague, unquantified claims — "significantly better," "industry-leading," "cutting-edge"',
        'Claims without named entity attribution — "studies show," "experts agree"',
        'Outdated statistics — figures more than 18 months old in rapidly-changing fields',
        'Generic overview content that covers a topic shallowly',
        'No clear topical authority signals — isolated pages without supporting content cluster',
        'Content that contradicts other pages on the same domain',
      ]},
    ],
  },
  {
    slug: 'retrieval-simulation-why-best-content-gets-skipped',
    title: 'Retrieval Simulation: Why Your Best Content Gets Skipped by AI',
    excerpt: 'Retrieval quality is not the same as content quality. A page can score well in every traditional metric and still fail at every stage of AI retrieval.',
    category: 'AI Visibility',
    publishedAt: 'May 17, 2025',
    readTime: 7,
    tags: ['Retrieval Simulation', 'AI Retrieval', 'Chunk Stability', 'Machine Readability'],
    content: [
      { type: 'p', text: 'There is a gap between content quality and retrieval quality that most publishers do not know exists. You can write a well-researched, well-structured, authoritative page — and it can still fail at every stage of AI retrieval. Not because the content is bad, but because the structural characteristics that make content retrieval-friendly are different from the characteristics that make content readable or well-ranked by traditional algorithms.' },
      { type: 'h2', text: 'The Six Stages of AI Retrieval' },
      { type: 'list', ordered: true, items: [
        'Chunk Extraction: content is split into semantic units — boundary placement determines which ideas survive intact',
        'Retrieval Ranking Pressure: your chunks compete against high-authority sources for the same query embedding',
        'Summarization Degradation: chunks are compressed by the AI — meaning that requires multi-chunk context is lost',
        'Context Truncation: content beyond the context window is never seen, regardless of quality',
        'Answer Formation: only chunks above a combined retrieval-quality threshold enter the answer',
        'Citation Eligibility Filtering: a final filter removes chunks below the specificity and authority threshold',
      ]},
      { type: 'h2', text: 'The Chunk Stability Problem' },
      { type: 'p', text: 'Chunk stability measures how consistently a piece of content is bounded across different chunking strategies. Content that spans multiple paragraph breaks, uses pronoun references that require prior context, or contains claims that are only meaningful in sequence will chunk differently depending on the retrieval system\'s tokenizer. The meaning that survives is random. High-stability content is written so that every paragraph could stand alone as a coherent, retrievable unit.' },
      { type: 'h2', text: 'Summarization Degradation' },
      { type: 'p', text: 'When AI systems compress retrieved chunks into answers, they make probabilistic decisions about what to keep. Claims that are explicit, self-contained, and specific survive compression. Claims that require context, use relative references, or are embedded in longer sentences lose specificity. The most vulnerable content is nuanced analysis that only makes sense in the context of the full argument — precisely the content that humans value most.' },
      { type: 'callout', variant: 'info', text: 'Fragile claims — assertions that require two or more chunks of context to be accurate — are the highest retrieval risk in most content. Count them. If you have more than 3 per 500 words, you have a summarization degradation problem.' },
      { type: 'h2', text: 'Improving Retrieval Quality' },
      { type: 'list', ordered: true, items: [
        'Write self-contained paragraphs: every paragraph should make one complete, verifiable point',
        'Avoid pronoun chains: use explicit entity names instead of "it," "they," "this concept"',
        'Put your most important claim first in each section, not as a conclusion',
        'Use FAQ structures for definitional content — these are retrieval-optimized by design',
        'Audit long pages for context window cutoffs — critical content past 3,000 words needs its own page',
      ]},
    ],
  },
  {
    slug: 'temporal-authority-content-freshness-ai-seo',
    title: 'Temporal Authority: Why Stale Content Is Now an Active Trust Penalty',
    excerpt: 'AI systems treat content age as a trust signal, not just a ranking factor. Understanding trust decay can prevent your best assets from becoming liabilities.',
    category: 'Machine Trust',
    publishedAt: 'May 15, 2025',
    readTime: 6,
    tags: ['Temporal Authority', 'Content Freshness', 'Trust Decay', 'AI SEO'],
    content: [
      { type: 'p', text: 'Traditional SEO treats content freshness as a ranking boost: newer content gets a temporary lift. But this model understates how AI systems use time as a signal. For AI retrieval systems, the age of content — and the pattern of updates — is not a boost factor. It is a trust signal. Content that has not been updated in six months is actively decaying in trust, regardless of its quality at the time it was published.' },
      { type: 'h2', text: 'How AI Systems Model Trust Decay' },
      { type: 'p', text: 'Trust decay is a model of how AI systems naturally down-weight content that has not received recent validation. The decay rate is not uniform: it varies by content type, by the time-sensitivity of the claims made, and by whether the content has any update signals (dateModified schema, HTTP last-modified headers, sitemap change frequency). A well-structured evergreen guide decays more slowly than a page containing statistics from a 2022 industry report.' },
      { type: 'h2', text: 'The Four Update Frequency Classifications' },
      { type: 'list', items: [
        'Actively Maintained (weekly+): highest trust stability, minimal decay penalty',
        'Periodically Maintained (monthly): moderate stability, slight decay on time-sensitive claims',
        'Stale (3+ months without update): accelerating decay on any recency-sensitive content',
        'Abandoned (6+ months without any signal): maximum decay, time-sensitive claims may be actively penalized',
      ]},
      { type: 'h2', text: 'Time-Sensitive Claims at Risk' },
      { type: 'p', text: 'Not all content decays at the same rate. Time-sensitive claims — those containing specific dates, statistics, version numbers, or references to current market conditions — carry an accelerated decay penalty when on stale pages. A product page with an accurate current price has no time-sensitive claim risk. A thought-leadership article asserting "the latest AI models show X" published two years ago has extreme time-sensitivity exposure. Identifying and updating (or removing) stale time-sensitive claims is one of the highest-ROI actions in temporal authority optimization.' },
      { type: 'callout', variant: 'tip', text: 'Add dateModified schema to every important page and update it when you change the content. Pages with schema-confirmed update dates receive a significantly lower decay rate than pages without any freshness signal.' },
      { type: 'h2', text: 'Temporal Authority Tactics' },
      { type: 'list', ordered: true, items: [
        'Implement dateModified schema on all key pages and update it on every content change',
        'Create a quarterly content audit process focused on time-sensitive claim accuracy',
        'Structure evergreen guides to separate durable analysis from time-sensitive data',
        'Use a "last verified" or "last reviewed" signal in content for long-form authority pages',
        'Add sitemap changefreq attributes that reflect actual update patterns, not aspirational ones',
      ]},
    ],
  },
  {
    slug: 'complete-guide-optimizing-google-ai-overviews',
    title: 'The Complete Guide to Optimizing for Google AI Overviews',
    excerpt: 'AI Overviews are the most prominent real estate in Google Search. Here\'s what actually drives inclusion — and what blocks it.',
    category: 'Strategy',
    publishedAt: 'May 12, 2025',
    readTime: 9,
    tags: ['Google AI Overviews', 'AI Search', 'Featured Snippets', 'Strategy'],
    content: [
      { type: 'p', text: 'Google AI Overviews represent the most significant restructuring of search result pages since the introduction of Featured Snippets. Appearing at the top of the results page for informational queries, they synthesize content from multiple sources into a generated answer — with citations to the sources that informed it. Inclusion in AI Overviews is not guaranteed by ranking first. It requires a specific combination of content signals that are distinct from traditional ranking factors.' },
      { type: 'h2', text: 'What Triggers an AI Overview' },
      { type: 'p', text: 'AI Overviews appear on informational queries where Google\'s systems have detected sufficient structured signal from multiple high-quality sources. Transactional queries, highly contested topics, and queries requiring real-time data generally do not trigger AI Overviews. The most common triggers are definitional queries ("What is X?"), procedural queries ("How do I X?"), and comparative queries ("What\'s the difference between X and Y?"). Each query type has different content requirements for inclusion.' },
      { type: 'h2', text: 'Content Requirements for AI Overview Inclusion' },
      { type: 'list', items: [
        'Featured snippet eligibility: a direct, concise answer to the query within the first 300 words',
        'FAQPage schema with question-answer pairs that match common query patterns on the topic',
        'E-E-A-T signals: clear authorship, organisational authority, and evidence of lived experience',
        'No noindex, no-snippet, or X-Robots-Tag directives on key content pages',
        'Content that directly answers the query rather than building up to an answer',
        'Schema markup that accurately describes the page type and content',
      ]},
      { type: 'h2', text: 'The AI Overview Optimization Checklist' },
      { type: 'list', ordered: true, items: [
        'Ensure H1 matches the primary query form for the page (question format preferred)',
        'Place a direct, specific answer to the query in the first two sentences after the H1',
        'Implement FAQPage schema for all question-format pages with verbatim body text in acceptedAnswer',
        'Add explicit author attribution with Person schema on every content page',
        'Remove any restrictive robots directives that limit AI snippet extraction',
        'Test snippet extraction manually: can the answer be extracted in under 50 words?',
      ]},
      { type: 'callout', variant: 'warning', text: 'Including meta name="robots" content="max-snippet:-1" is critical for AI Overview eligibility. Any restriction on snippet length can exclude your content from AI Overview consideration, regardless of content quality.' },
      { type: 'h2', text: 'Monitoring Your AI Overview Presence' },
      { type: 'p', text: 'AI Overview appearance is query-specific and changes over time as Google\'s systems re-evaluate sources. Track the specific queries for which your content appears in AI Overviews using Search Console data alongside manual testing. When you lose an inclusion, compare the content structure of the source that replaced you — the difference is usually in answer directness or schema completeness, not in overall content quality.' },
    ],
  },
  {
    slug: 'four-layer-ai-intelligence-stack-seo',
    title: 'The Four-Layer AI Intelligence Stack Every SEO Needs to Understand',
    excerpt: 'Most SEO tools operate at Layer 1. Machine trust and AI citation live at Layer 4. Understanding the architecture clarifies why traditional audits miss most of what matters.',
    category: 'Strategy',
    publishedAt: 'May 10, 2025',
    readTime: 7,
    tags: ['AI Strategy', 'Intelligence Layers', 'Machine Trust', 'AI SEO'],
    content: [
      { type: 'p', text: 'The tools most SEOs use every day operate at Layer 1: the crawl and structure layer. They check titles, metas, canonicals, broken links, sitemap health. These signals are necessary but no longer sufficient. As AI systems take an increasingly direct role in how content is discovered and consumed, the layers above Layer 1 become the primary battleground for visibility. Understanding the four-layer model clarifies why a site can be technically perfect at Layer 1 and completely invisible at Layers 3 and 4.' },
      { type: 'h2', text: 'Layer 1 — Crawl and Structure' },
      { type: 'p', text: 'The foundation layer covers the technical infrastructure of AI accessibility: can AI systems reach and render your content? Does your robots.txt allow relevant crawlers? Are your pages indexable? Is your internal link architecture sound enough to distribute PageRank to important pages? Does your sitemap accurately represent the site? Layer 1 failures block everything above them — they are the floor, not the ceiling, of AI visibility.' },
      { type: 'h2', text: 'Layer 2 — Semantic Intelligence' },
      { type: 'p', text: 'Layer 2 is where content becomes meaningful to machines. Entity detection and consistency, schema markup accuracy, content quality and topical depth, chunk boundary quality, boilerplate ratio — these are the signals that determine whether AI systems can extract a coherent, accurate understanding from your pages. Most sites pass Layer 1 and fail Layer 2. The gap is almost always in entity consistency and schema alignment.' },
      { type: 'h2', text: 'Layer 3 — AI Visibility' },
      { type: 'p', text: 'Layer 3 models the AI-specific visibility signals: machine readability, AI extractability, retrieval readiness, citation probability, and semantic trust. A Layer 3 analysis answers the question: assuming an AI system can access and understand your content (Layers 1 and 2), how likely is it to retrieve and cite it? Layer 3 failures are usually about content structure and claim quality, not technical implementation.' },
      { type: 'h2', text: 'Layer 4 — Machine Trust' },
      { type: 'p', text: 'Layer 4 is the highest and most differentiating layer: retrieval simulation, machine trust scoring, temporal authority, recommendation surface mapping, and synthetic entity detection. It answers the question that no other layer addresses: over time, as AI systems continue to process and evaluate your domain, are you building trust or losing it? Layer 4 analysis requires multiple audit snapshots and access to historical data. It is the layer where competitive advantage in AI search is won or lost.' },
      { type: 'callout', variant: 'info', text: 'You cannot skip layers. A site with Layer 4 investment and Layer 2 entity failures will still underperform a well-optimized Layer 3 site. Each layer depends on the one below it.' },
    ],
  },
  {
    slug: 'semantic-clarity-vs-keyword-density-ai-search',
    title: 'Semantic Clarity vs. Keyword Density: What AI Search Actually Rewards',
    excerpt: 'The keyword era is over. AI retrieval systems optimize for semantic clarity — a fundamentally different writing discipline.',
    category: 'AI Visibility',
    publishedAt: 'May 7, 2025',
    readTime: 5,
    tags: ['Semantic SEO', 'AI Writing', 'Content Optimization', 'Keyword Strategy'],
    content: [
      { type: 'p', text: 'For two decades, keyword density was the core metric of search-oriented writing. The idea was straightforward: use your target keyword frequently enough, in enough prominent positions, and search engines would classify your page as relevant. AI retrieval systems broke this model completely. They don\'t count keyword occurrences. They embed the full semantic meaning of your content and compare it against the embedding of a query. Keyword stuffing doesn\'t just fail to help — in some contexts, it actively reduces semantic clarity.' },
      { type: 'h2', text: 'Why Keywords Don\'t Predict AI Citation' },
      { type: 'p', text: 'AI systems retrieve content by comparing vector embeddings — compressed mathematical representations of semantic meaning. A document that clearly and precisely defines an entity, explains its relationships, and supports its claims with specific evidence will have a higher embedding similarity to related queries than a document that repeats the target keyword 15 times but never achieves semantic precision. The optimization target has shifted from "signal relevance" to "achieve clarity."' },
      { type: 'h2', text: 'What Semantic Clarity Means Operationally' },
      { type: 'list', items: [
        'Every entity is named explicitly and consistently — no pronoun references without prior explicit mention',
        'Claims are stated in the form "[Entity] [verb] [specific attribute]" rather than vague assertions',
        'Terminology is consistent throughout the document — synonyms create semantic ambiguity',
        'The scope of each section is explicit — what this section covers and what it does not',
        'Relationships between entities are stated, not implied — "X is a type of Y," not "X and Y are related"',
      ]},
      { type: 'h2', text: 'Measuring Semantic Clarity' },
      { type: 'p', text: 'Semantic clarity has measurable proxies: entity extraction rate (how many named entities can be identified per 500 words?), disambiguation score (are those entities uniquely identifiable from body text alone?), chunk extractability (can each paragraph be understood without reading the surrounding paragraphs?), and summarizability (does the content compress into a coherent 50-word summary without distortion?).' },
      { type: 'callout', variant: 'tip', text: 'Test semantic clarity with this exercise: copy any 300-word section of your page and give it to someone unfamiliar with your brand. Can they correctly identify your primary entity, your key claim, and your supporting evidence? If not, you have a semantic clarity problem that no keyword optimization will fix.' },
      { type: 'h2', text: 'Writing for Semantic Clarity' },
      { type: 'list', ordered: true, items: [
        'Lead with definition: introduce every entity by type before discussing its attributes',
        'Use entity names, not pronouns: "SiteNexis analyzes..." not "It analyzes..."',
        'One claim per sentence, one topic per paragraph',
        'State relationships explicitly: "Machine Trust Score is a component of the Layer 4 intelligence stack"',
        'Avoid hedging synonyms: use consistent terminology throughout the document',
      ]},
    ],
  },
  {
    slug: 'voice-search-seo-ai-audio-retrieval',
    title: 'Voice Search SEO: Structuring Content for AI Audio Retrieval',
    excerpt: 'Voice queries have fundamentally different structural requirements than text queries. Most sites are structurally invisible to voice assistants.',
    category: 'Strategy',
    publishedAt: 'May 5, 2025',
    readTime: 6,
    tags: ['Voice Search', 'AI Assistants', 'Speakable Schema', 'Local SEO'],
    content: [
      { type: 'p', text: 'Voice assistants — Siri, Google Assistant, Alexa, and their AI-enhanced successors — retrieve content differently from chat-based AI systems. They operate under tight answer length constraints (typically under 30 words for spoken responses), prioritize direct factual claims that can be stated aloud without context, and rely heavily on structured data for source selection. A site optimized for text-based AI retrieval is not automatically optimized for voice retrieval.' },
      { type: 'h2', text: 'How Voice Assistants Select Content' },
      { type: 'p', text: 'Voice assistant source selection heavily weights the presence of speakable schema, the directness of answers, and the structured data completeness of business entities. A query for "What is [Company]\'s phone number?" will return the answer from Organization schema, not from body text. A query for "Explain [Concept] simply" will look for content explicitly marked as speakable with a clear, concise definition. Text that requires visual presentation — tables, diagrams, lists — is systematically deprioritized.' },
      { type: 'h2', text: 'The Speakable Schema Property' },
      { type: 'p', text: 'The SpeakableSpecification schema property tells voice assistants exactly which sections of your content are suitable for audio delivery. When implemented correctly, it identifies specific CSS selectors or xPath expressions that point to the retrievable sections. Effective speakable markup targets: the introductory definition in the first paragraph, direct answers to FAQ entries, key factual claims stated in a single sentence. Each speakable section should be under 30 words and self-contained.' },
      { type: 'callout', variant: 'tip', text: 'Write your page\'s first paragraph as a direct, 20-25 word definition of the primary topic. This single section, when marked as speakable, can capture voice queries for the entire topical cluster your page covers.' },
      { type: 'h2', text: 'Local Business Voice Optimization' },
      { type: 'p', text: 'For local businesses, voice optimization is tied directly to NAP consistency (Name, Address, Phone) across schema, Google Business Profile, and all directory listings. Voice assistants cross-reference these signals before delivering a spoken answer. Any inconsistency — a different address format, an old phone number, a different business name variant — creates a validation failure that can prevent voice retrieval entirely.' },
      { type: 'h2', text: 'Voice Optimization Checklist' },
      { type: 'list', ordered: true, items: [
        'Add SpeakableSpecification schema to pages with concise, self-contained factual claims',
        'Write FAQ answers in under 30 words, in a form that reads naturally aloud',
        'Ensure Organization / LocalBusiness schema name matches Google Business Profile exactly',
        'Verify NAP consistency across all directory listings',
        'Structure key definitions as standalone sentences in the first paragraph of each section',
      ]},
    ],
  },
  {
    slug: 'how-chatgpt-perplexity-claude-choose-citations',
    title: 'How ChatGPT, Perplexity, and Claude Choose What to Cite',
    excerpt: 'Each major AI system has different retrieval and citation behavior. Understanding provider-specific patterns is the key to multi-surface AI visibility.',
    category: 'AI Visibility',
    publishedAt: 'May 3, 2025',
    readTime: 8,
    tags: ['ChatGPT SEO', 'Perplexity SEO', 'Claude SEO', 'Multi-AI Strategy'],
    content: [
      { type: 'p', text: 'Not all AI systems retrieve and cite content the same way. ChatGPT with browsing, Perplexity, Claude, and Google AI Overviews each have distinct retrieval architectures, different trust models, and different citation behaviors. A content strategy that optimizes only for one surface will leave significant AI visibility opportunities unrealized. Understanding the behavioral matrix of the major AI providers is the foundation of multi-surface AI content strategy.' },
      { type: 'h2', text: 'Provider-Specific Retrieval Behavior' },
      { type: 'list', items: [
        'Google AI Overviews: weights E-E-A-T signals, structured data, and featured snippet eligibility. Citation behavior is direct answer extraction with source attribution.',
        'ChatGPT (browsing / RAG): weights semantic similarity to query embedding and recency. Citation behavior is chunk-level quotation with URL.',
        'Perplexity: uses real-time crawl with semantic ranking. Weights source diversity and answer directness. Inline citation with URL.',
        'Claude (web search): weights semantic clarity and factual structure. Weights authoritativeness and entity clarity. Summarization with attribution.',
        'Gemini: weights Knowledge Graph integration. Entity consistency and schema directly affect inclusion probability.',
      ]},
      { type: 'h2', text: 'What All AI Systems Prioritize' },
      { type: 'p', text: 'Despite their differences, all major AI providers share a set of core content requirements. Factual density and claim specificity are universally rewarded. Entity clarity — the unambiguous identification of the primary entity being discussed — is valued across all providers. The absence of contradictions, both within a page and across a domain, improves performance on every surface. Structural trust signals, particularly schema markup accuracy, are increasingly universal.' },
      { type: 'callout', variant: 'info', text: 'SiteNexis models all surface scores as probabilistic estimates based on measurable content signals — not live queries to AI providers. Provider behavior changes, and these estimates are updated as new patterns are identified.' },
      { type: 'h2', text: 'Provider-Specific Optimization Priorities' },
      { type: 'list', items: [
        'For Google AI Overviews: prioritize FAQPage schema, direct answer structure, and E-E-A-T signals',
        'For ChatGPT: prioritize recency, semantic precision in chunk units, and structured factual claims',
        'For Perplexity: prioritize answer directness, source diversity signals, and clear topical focus per page',
        'For Claude: prioritize factual accuracy, entity clarity, and absence of hedging language',
        'For Gemini: prioritize Knowledge Graph entity alignment and schema completeness',
      ]},
      { type: 'h2', text: 'The Multi-Provider Content Challenge' },
      { type: 'p', text: 'The good news is that the baseline for strong multi-provider performance is consistent: entity clarity, schema accuracy, factual density, and structural trust signals. A site that performs these well will outperform on most AI surfaces. Provider-specific optimization is the 20% effort that addresses the remaining gaps after the foundation is solid. Build the foundation first. Target specific providers second.' },
    ],
  },
  {
    slug: 'technical-seo-audit-is-dead-what-comes-next',
    title: 'The Technical SEO Audit Is Dead. Here\'s What Comes Next.',
    excerpt: 'Crawl health and title tags are table stakes. The new audit disciplines — machine trust, retrieval simulation, entity intelligence — are where competitive advantage now lives.',
    category: 'Strategy',
    publishedAt: 'April 28, 2025',
    readTime: 6,
    tags: ['Technical SEO', 'AI SEO', 'SEO Strategy', 'Auditing'],
    content: [
      { type: 'p', text: 'The traditional technical SEO audit was built for a specific era: the era when search engines primarily consumed HTML. Check title tags. Check meta descriptions. Verify canonical implementation. Audit internal links. Fix broken pages. This checklist was valuable when the primary consumer of your content was a search engine bot doing keyword-frequency analysis. It is still necessary. But it is no longer sufficient. The consumer has changed. The audit must change with it.' },
      { type: 'h2', text: 'What Traditional Audits Miss' },
      { type: 'list', items: [
        'AI extractability: whether your content survives the chunk extraction pipeline intact',
        'Entity consistency: whether your primary entity is described consistently across all pages and all schema types',
        'Machine trust signals: entity credibility, schema-to-body alignment, contradiction detection',
        'Retrieval simulation: which content would actually be retrieved under query pressure from competitors',
        'Temporal authority: whether your content is decaying in trust due to stale time-sensitive claims',
        'Recommendation surface coverage: which AI surfaces are you visible on, and which are you structurally absent from',
      ]},
      { type: 'h2', text: 'The Machine Readability Gap' },
      { type: 'p', text: 'The most surprising finding in AI visibility audits is how often technically healthy sites fail machine readability analysis. A site can have a perfect technical foundation — fast, crawlable, properly canonicalized, schema-rich — and still achieve a machine readability score below 50. The gap is almost always in boilerplate ratio (too much content that gets filtered before chunking) and chunk extractability (too many paragraphs that only make sense in context).' },
      { type: 'callout', variant: 'warning', text: 'A perfect technical SEO audit is now a minimum requirement, not a competitive advantage. The differentiation between AI-visible and AI-invisible sites is at Layer 2 and above — in semantic intelligence and machine trust, not in technical foundations.' },
      { type: 'h2', text: 'The New Audit Disciplines' },
      { type: 'list', items: [
        'Entity Intelligence Audit: entity detection rate, consistency score, disambiguation, sameAs validation',
        'Machine Readability Audit: boilerplate ratio, chunk boundary quality, extraction fidelity score',
        'Citation Probability Audit: factual density, claim specificity, topical authority depth per page',
        'Machine Trust Audit: contradiction detection, schema alignment, trust degradation signals',
        'Retrieval Simulation: chunk stability index, answer formation probability, citation eligibility score',
      ]},
    ],
  },
  {
    slug: 'internal-linking-for-ai-systems-beyond-pagerank',
    title: 'Internal Linking for AI Systems: Beyond PageRank',
    excerpt: 'Internal links don\'t just pass equity — they define the entity relationship graph that AI systems use to model your site\'s semantic authority.',
    category: 'Technical SEO',
    publishedAt: 'April 25, 2025',
    readTime: 6,
    tags: ['Internal Linking', 'PageRank', 'Entity Relationships', 'Link Architecture'],
    content: [
      { type: 'p', text: 'Internal link architecture has always been important for SEO — primarily for distributing PageRank and signaling page hierarchy to search engines. In the AI retrieval model, internal links serve an additional function that is equally important: they define the entity relationship graph. When page A links to page B in the context of discussing entity X, the AI system infers a semantic relationship between the entities on both pages. The structure of your internal links shapes the AI\'s cognitive model of your domain.' },
      { type: 'h2', text: 'How AI Systems Use Internal Links' },
      { type: 'p', text: 'Beyond PageRank distribution, AI retrieval systems extract entity relationship signals from internal link patterns. A topic cluster — a hub page that links to multiple supporting pages on related subtopics — signals deep topical authority. A site where every page links to every other page signals noise, not depth. A site with orphaned high-value pages misses the opportunity to connect those pages\' authority into the semantic graph of surrounding content.' },
      { type: 'h2', text: 'Entity Relationship Mapping Through Links' },
      { type: 'p', text: 'The anchor text of internal links is a direct input to the entity relationship model. "Learn more about our enterprise pricing" links a page to a topic. "How Machine Trust Score is calculated" links a page to a specific entity attribute. The more specific and entity-relevant your anchor text, the stronger the entity relationship signal. Generic anchors like "click here" or "read more" contribute noise to the entity graph, not structure.' },
      { type: 'h2', text: 'The AI Perception Graph and Link Architecture' },
      { type: 'p', text: 'The AI Perception Graph is a model of how an AI system internally represents a site\'s semantic content — not its link structure, but its meaning structure. Internal links are a major input to this model. Sites with strong topical clusters — where pages on related entities consistently link to each other with entity-relevant anchor text — achieve higher AI Perception Graph density, which correlates directly with recommendation confidence scores.' },
      { type: 'callout', variant: 'tip', text: 'Audit your anchor text distribution. If more than 30% of your internal links use generic anchor text (learn more, click here, read this), you are under-utilizing one of the most efficient entity relationship signals available to you.' },
      { type: 'h2', text: 'Internal Linking Tactics for AI' },
      { type: 'list', ordered: true, items: [
        'Link from entity mentions: every time you name a key entity in body text, link to that entity\'s primary page',
        'Build topic clusters: hub pages should link to 5–10 supporting pages; supporting pages should link back to the hub',
        'Use entity-attribute anchor text: "how Machine Trust Score is calculated" > "learn more"',
        'Eliminate orphaned authority pages: every important page should receive at least three relevant internal links',
        'Audit for link dilution: pages with 50+ outbound internal links distribute so little equity they risk being ignored',
      ]},
    ],
  },
  {
    slug: 'synthetic-entity-detection-what-seos-need-to-know',
    title: 'Synthetic Entity Detection: What SEOs Need to Know',
    excerpt: 'AI systems are now detecting patterns that indicate manipulated entity authority. Understanding synthetic signals helps you identify and fix inadvertent trust penalties.',
    category: 'Machine Trust',
    publishedAt: 'April 22, 2025',
    readTime: 7,
    tags: ['Synthetic Entities', 'Machine Trust', 'Entity Authenticity', 'AI Trust'],
    content: [
      { type: 'p', text: 'As AI systems have become primary consumers of web content, a new category of manipulation has emerged: synthetic entity signals. These are entity profiles, authority networks, and citation structures that have been created or amplified to appear authoritative to AI retrieval systems rather than reflecting genuine, verifiable authority. AI systems are now sophisticated enough to detect the structural signatures of synthetic authority — and they penalize it. More importantly, legitimately-built sites can inadvertently exhibit synthetic patterns without any intent to manipulate.' },
      { type: 'h2', text: 'What Is a Synthetic Entity?' },
      { type: 'p', text: 'A synthetic entity is an entity whose claimed authority is not supported by independent external validation. This can be a person entity with no verifiable external presence despite prominent claims of expertise. It can be an organisation entity whose claimed founding date, location, or team cannot be confirmed from any source outside the domain. It can be a network of supporting pages that all cite each other without any external validation of the underlying claims. The pattern, not the intent, is what triggers detection.' },
      { type: 'h2', text: 'The Five Synthetic Patterns AI Systems Detect' },
      { type: 'list', ordered: true, items: [
        'Fake Entity Profiles: entities with no verifiable external presence claiming high authority',
        'AI Authority Networks: clusters of sameAs links pointing to recently-created profiles with no independent history',
        'Schema Manipulation: schema claiming aggregate review ratings, authority credentials, or dates not evidenced in body text',
        'Citation Farming: pages that cite only other pages on the same domain for "factual" claims with no external validation',
        'Unnatural Clustering: entity relationship graphs with abnormally high reciprocal link density or implausible topical breadth',
      ]},
      { type: 'callout', variant: 'info', text: 'Synthetic detection is probabilistic, not binary. SiteNexis reports an Entity Authenticity Confidence score (0–100) with detection confidence scores per pattern. High confidence findings should be investigated; low confidence findings are informational.' },
      { type: 'h2', text: 'How Legitimate Sites Trigger Synthetic Signals' },
      { type: 'p', text: 'Many legitimate sites inadvertently exhibit synthetic patterns. A company that has not yet earned external validation (no Wikipedia entry, no news coverage, no directory listings) will have no external sameAs validation — which looks identical to a synthetic entity. An author page with a professional bio but no linked external profiles creates the same signal as a fabricated author. These are not manipulation — they are omissions that can be corrected.' },
      { type: 'h2', text: 'The Entity Authenticity Confidence Score' },
      { type: 'p', text: 'The Entity Authenticity Confidence score (inverse of synthetic risk) measures the degree to which your entity signals appear organic rather than manufactured. The most impactful improvements are: adding sameAs links to external sources that independently confirm your entity attributes, ensuring author entities have verifiable external profiles, and reviewing schema claims to remove anything not evidenced in body text. A score improvement from 45 to 75 in Entity Authenticity directly improves Machine Trust Score.' },
      { type: 'h2', text: 'Improving Your Authenticity Score' },
      { type: 'list', ordered: true, items: [
        'Add sameAs links to Wikipedia, Wikidata, LinkedIn, Companies House, or equivalent for your primary entity',
        'Ensure all author entities have externally verifiable profiles with matching names and attributes',
        'Remove or update any schema claims that cannot be confirmed from body text on the same page',
        'Build a citation portfolio from external domains that independently discuss your entity',
        'Audit your internal citation patterns — over-reliance on self-citation is a farming signal',
      ]},
    ],
  },
]

export function getPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug)
}

export function getRelatedPosts(current: BlogPost, limit = 3): BlogPost[] {
  return BLOG_POSTS
    .filter(p => p.slug !== current.slug && p.category === current.category)
    .slice(0, limit)
}
