import type { Metadata } from 'next';
import { MarketingNav } from '@/components/marketing/MarketingNav';
import { Footer } from '@/components/marketing/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service — SiteNexis',
  description: 'SiteNexis terms of service — the rules governing use of the platform.',
  alternates: { canonical: '/terms' },
};

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using SiteNexis, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you do not have permission to access the service.',
  },
  {
    title: '2. Description of Service',
    body: 'SiteNexis provides AI visibility intelligence, machine trust analysis, and retrieval simulation for web content. The service is provided "as is" for informational purposes. All scores are estimates derived from measurable content signals and do not constitute guarantees of AI system behavior.',
  },
  {
    title: '3. Account Responsibilities',
    body: 'You are responsible for maintaining the security of your account credentials. You must not share account access with others outside of team seats included in your plan. You must not use the service to audit domains you do not own or have explicit permission to audit.',
  },
  {
    title: '4. Acceptable Use',
    body: 'You must not use SiteNexis to: (a) attempt to manipulate AI retrieval systems in ways that harm users or competitors; (b) systematically scrape or extract data for resale; (c) audit competitor domains for the purpose of competitive sabotage; (d) reverse-engineer the scoring algorithms for the purpose of gaming them rather than improving content quality.',
  },
  {
    title: '5. Subscription and Billing',
    body: 'Paid subscriptions are billed monthly or annually as selected. Upgrades take effect immediately with prorated billing. Downgrades take effect at the next billing cycle. All payments are processed through Stripe. SiteNexis does not store payment card information.',
  },
  {
    title: '6. Data and Privacy',
    body: 'Your use of the service is also governed by our Privacy Policy. Audit data generated by your account is yours. SiteNexis may use aggregated, anonymised data to improve scoring accuracy. We do not sell your data to third parties.',
  },
  {
    title: '7. Intellectual Property',
    body: 'The SiteNexis platform, scoring algorithms, and brand assets are proprietary. PDF reports generated by the service may be used by you for internal business purposes. You may not resell or redistribute audit reports without a white-label licence (Agency/Enterprise plans).',
  },
  {
    title: '8. Limitation of Liability',
    body: 'SiteNexis is not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability for any claim is limited to the amount paid by you in the 12 months preceding the claim.',
  },
  {
    title: '9. Termination',
    body: 'You may cancel your subscription at any time from Account Settings. SiteNexis reserves the right to suspend or terminate accounts that violate these terms, with or without notice.',
  },
  {
    title: '10. Changes to Terms',
    body: 'We may update these terms from time to time. Material changes will be communicated by email with at least 14 days notice. Continued use of the service after the effective date constitutes acceptance of the updated terms.',
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-midnight font-ui text-white antialiased">
      <MarketingNav />
      <div className="mx-auto max-w-3xl px-6 pb-24 pt-32">
        <h1 className="mb-2 text-[36px] font-bold tracking-[-0.02em] text-white">Terms of Service</h1>
        <p className="mb-12 text-[14px] text-slate-500">Last updated: July 2026</p>
        <div className="space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="mb-3 text-[17px] font-semibold text-white">{s.title}</h2>
              <p className="text-[14px] leading-[1.75] text-slate-400">{s.body}</p>
            </section>
          ))}
        </div>
        <div className="mt-12 rounded-xl border border-white/[0.06] bg-white/[0.02] p-6">
          <p className="text-[14px] text-slate-400">
            Questions about these terms? Contact us at{' '}
            <a href="mailto:sitenexisintel@gmail.com" className="text-cyan hover:underline">
              sitenexisintel@gmail.com
            </a>
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
